# Generated by Django 5.2.8 on 2025-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.CharField(max_length=200, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
            ],
        ),
    ]
