# Generated by Django 5.2.8 on 2025-11-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
