# Generated by Django 5.2.8 on 2025-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_alter_attendee_qr_code_alter_attendee_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
